name = "Create: Factory Floor"
author = "https://github.com/Innovators-of-Create"
version = "1.0.10-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d75fb10e5efc7c96523878d37f5613036064fe6b923a653f49eeb84cc51bfd9a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = []
