name = "Create: Factory Floor"
author = "https://github.com/Innovators-of-Create"
version = "1.0.8-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60cf69ff17a28d677d4a256b946d5e818cc7470ac8fe3db9c4cf820680944b8c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = []
