name = "Create: Factory Floor"
author = "https://github.com/Innovators-of-Create"
version = "1.0.3-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc5a981691133f8eff9c1fedff921315a323895f09876ab8bae26432e545d407"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = []
