name = "Create: Factory Floor"
author = "https://github.com/Innovators-of-Create"
version = "1.0.8-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f904d78970ea6091400b1e5d868973f23a9ccad0e1efc54b95a67175c5130767"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = []
