name = "Create: Factory Floor"
author = "https://github.com/Innovators-of-Create"
version = "1.0.16-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08168b0389c1311e73860b726f3e07ed69b5e9441b4c34e9833627ee0bb2c75d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = []
